### ISSUE TITLE
Create migration documentation

### ISSUE THREAD

**Issue by Realiserad** [Realiserad/adcs-deployment#9]
# Import a backup of an issuing CA

The documentation works well when setting up a new ADCS installation, but not so well when migrating an existing one.

Currently it is possible to migrate an existing root CA instead of creating a new one by specifying the following in ``group_vars/all.yml``
```
servers:
  root_ca:
    location:
      existing_backup: Z:\
```

This would generate instructions for how to import a backup of an existing root CA backed up to ``Z:\`` instead of generating a keypair for a new one.

Make it possible to do something similar for the issuing CAs. Since nothing needs to be signed from the root, it should be possible to remove the definition of the root CA from the YML without build failures.

# Enable a different set of templates for each CA

At the moment, all templates defined in the YML are enabled on all CAs. Since it is now possible to generate documentation for how to set up multiple issuing CAs, it should also be possible to enable a different set of templates for each CA by defining the templates in the YML:
```
servers:
  issuing_cas:
    cn: CA 1
    templates:
    - First template to enable on CA 1
    - Second template to enable on CA 1 
```

# Reuse existing templates from AD

It should be possible to completely eliminate the ``templates`` section from the YML, assuming there are already templates set up in AD from an old installation.

# Reuse existing CDP and AIA URLs

It should be possible to use existing CDP and AIA URLs from the old installation, or at least add instructions for how to add redirects from the old URLs to the new ones, to not break validation of certificates issued from the old PKI.

# Test backup and restore

Generate instructions for how to test a backup restore procedure before a service window is announced.

# Add support for enrollment servers

It should be possible to add access for existing enrollment servers when configuring the CA.
